### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by xda3mon** [FlowCrypt/GMP#3]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/26290271/230569769-3dfb7d74-dba6-4b07-b1c4-798d1e81c7cc.png">

**Comment by tomholub** [comment]
@sosnovsky are we still using GMP on iOS?

**Comment by sosnovsky** [comment]
> @sosnovsky are we still using GMP on iOS?

No, it was used only for some `openpgp` functions which were executed in Swift (for better performance). But after upgrading to `openpgp v5` it's not needed anymore.

I created PR for removing GMP dependency - https://github.com/FlowCrypt/flowcrypt-ios/pull/2176

**Comment by tomholub** [comment]
ok. in that case, we can archive, and eventually remove this repo
